export enum ActionType {
  SEARCH = "SEARCH",
  SEARCH_SUCCESS = "SEARCH_SUCCESS",
  SEARCH_ERROR = "SEARCH_ERROR",
  INGREDIENTS_FETCH = "INGREDIENTS_FETCH",
  INGREDIENTS_FETCH_SUCCESS = "INGREDIENTS_FETCH_SUCCESS",
  INGREDIENTS_FETCH_ERROR = "INGREDIENTS_FETCH_ERROR",
  INGREDIENT_SELECT = "INGREDIENTS_SELECT",
}
